name: Go

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@v0.2.0

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@v0.2.0
